# docker-compose.yml

version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  streamlit_app:
    build: .
    container_name: streamlit_app
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]

  telegram_bot:
    build: .
    container_name: telegram_bot
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    command: ["python", "bot.py"]

volumes:
  mongo-data:
